// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2o2Vkfx4DNsc667CrW4piaursLizPRR0',
    appId: '1:473778610568:web:201a0cd4ee54a22b97da3d',
    messagingSenderId: '473778610568',
    projectId: 'realestatecalc-flutter',
    authDomain: 'realestatecalc-flutter.firebaseapp.com',
    storageBucket: 'realestatecalc-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgHAjgU4jM4QQqzzKiLSidPGt6cDkP7Gg',
    appId: '1:473778610568:android:72011de341d265b197da3d',
    messagingSenderId: '473778610568',
    projectId: 'realestatecalc-flutter',
    storageBucket: 'realestatecalc-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk9bzu4NP7N5n_WiUpiyRvOMaRPyCLp5A',
    appId: '1:473778610568:ios:53d367e2a95a483997da3d',
    messagingSenderId: '473778610568',
    projectId: 'realestatecalc-flutter',
    storageBucket: 'realestatecalc-flutter.appspot.com',
    iosClientId:
        '473778610568-0r32625aj1sj5jrfpo2t6trbdnrga0bk.apps.googleusercontent.com',
    iosBundleId: 'com.example.calcFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk9bzu4NP7N5n_WiUpiyRvOMaRPyCLp5A',
    appId: '1:473778610568:ios:53d367e2a95a483997da3d',
    messagingSenderId: '473778610568',
    projectId: 'realestatecalc-flutter',
    storageBucket: 'realestatecalc-flutter.appspot.com',
    iosClientId:
        '473778610568-0r32625aj1sj5jrfpo2t6trbdnrga0bk.apps.googleusercontent.com',
    iosBundleId: 'com.example.calcFront',
  );
}
